export { default as Main } from "./Main/Main";
export { default as Login } from "./Login/Login";
export { default as Signup } from "./Signup/Signup";
export { default as PassbookInfo } from "./PassbookInput/PassbookInfo";
export { default as HousingInfo } from "./HousingInput/HousingInfo";
export { default as MemberInfo } from "./MemberInput/MemberInfo";
export { default as MemberHousingInfo } from "./MemberHousingInput/MemberHousingInfo";
export { default as Board } from "./AddMember/Board";
export { default as Post } from "./AddMember/Post";
export { default as PersonalInfo} from './CommonInput/PersonalInfo';
export { default as BoardMain} from './CaseBoard/BoardMain';
export { default as BoardView } from './CaseBoard/BoardView';
export { default as FAQ } from './FAQ/FAQ';